# Generated by Django 6.0.3 on 2026-03-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuvchi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashinalar',
            name='brand',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mashinalar',
            name='color',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
