# Generated by Django 6.0.3 on 2026-03-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuvchi', '0002_mashinalar_brand_mashinalar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashinalar',
            name='engine_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mashinalar',
            name='fuel_type',
            field=models.CharField(default='Benzin', max_length=50),
        ),
        migrations.AddField(
            model_name='mashinalar',
            name='transmission',
            field=models.CharField(default='Mexanika', max_length=50),
        ),
        migrations.AddField(
            model_name='mashinalar',
            name='turi',
            field=models.CharField(default='Sedan', max_length=100),
        ),
        migrations.AddField(
            model_name='mashinalar',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
